database:
    ip: '10.10.1.19'
    
other:
    to_email: 'boss@mycompany.com'
    bins: [
    'A1A1', 'A1A2', 'A1B1', 'A1B2', 'A1B3', 'A1C1', 'A1C2', 'A1C3',
    'A2A1', 'A2A2', 'A2B1', 'A2B2', 'A2B3', 'A2C1', 'A2C2', 'A2C3',
    'A3A1', 'A3A2', 'A3B1', 'A3B2', 'A3B3', 'A3C1', 'A3C2', 'A3C3',
    'A4A1', 'A4A2', 'A4B1', 'A4B2', 'A4B3', 'A4C1', 'A4C2', 'A4C3',
    'A5A1', 'A5A2', 'A5B1', 'A5B2', 'A5B3', 'A5C1', 'A5C2', 'A5C3',
    'A6A1', 'A6A2', 'A6B1', 'A6B2', 'A6B3', 'A6C1', 'A6C2', 'A6C3',
    'A7A1', 'A7A2', 'A7B1', 'A7B2', 'A7B3', 'A7C1', 'A7C2', 'A7C3',
    'A9A1', 'A9A2', 'A9B1', 'A9B2', 'A9B3', 'A9C1', 'A9C2', 'A9C3',
    'A10A1', 'A10A',
    'A11A1', 'A11A2', 'A11B1', 'A11B2', 'A11B3', 'A11C1', 'A11C2', 'A11C3',
    'A12A1', 'A12A2', 'A12B1', 'A12B2', 'A12B3', 'A12C1', 'A12C2', 'A12C3',
    'A13A1', 'A13A2', 'A13B1', 'A13B2', 'A13B3', 'A13C1', 'A13C2', 'A13C3',
    'B9A1', 'B9A2', 'B9B1', 'B9B2', 'B9B3', 'B9C1', 'B9C2', 'B9C3',
    'B10A1', 'B10A2', 'B10B1', 'B10B2', 'B10B3', 'B10C1', 'B10C2', 'B10C3',
    'B11A1', 'B11A2', 'B11B1', 'B11B2', 'B11B3', 'B11C1', 'B11C2', 'B11C3',
    'B12A1', 'B12A2', 'B12B1', 'B12B2', 'B12B3', 'B12C1', 'B12C2', 'B12C3',
    'B13A1', 'B13A2',
    'Z1A1', 'Z1A2', 'Z1B1', 'Z1B2', 'Z1B3', 'Z1C1', 'Z1C2', 'Z1C3',
    'Z2A1', 'Z2A2', 'Z2B1', 'Z2B2', 'Z2B3', 'Z2C1', 'Z2C2', 'Z2C3',
    'Z3A1', 'Z3A2', 'Z3B1', 'Z3B2', 'Z3B3', 'Z3C1', 'Z3C2', 'Z3C3',
    'Z4A1', 'Z4B1', 'Z4C1', 'Z4D1',
    'Z5A1', 'Z5A2', 'Z5B1', 'Z5B2', 'Z5C1', 'Z5C2',
    'Z6A1', 'Z6A2', 'Z6B1', 'Z6B2', 'Z6C1', 'Z6C2',
    'X1A1', 'X1B1', 'X1C1', 'X1D1',
    'X2A1', 'X2B1', 'X2C1', 'X2D1',
    'X3A1', 'X3B1', 'X3C1', 'X3D1',
    'X4A1', 'X4A2', 'X4A3','X4B1', 'X4B2','X4B3',
    'X5A1', 'X5B1', 'X5C1', 'X5D1',
    'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10'
    ]